###
GET http://localhost:7000/sign-in
Content-type: application/json

###

POST http://localhost:7000/sign-in
Content-type: application/json

{
  "email":"useutttttuuur1@mail.com",
  "name":"sdfsdf",
  "password":"fdsfsdf",
  "passwordConfirmation":"fdsfsdf",
  "username":"sadasdsad",
  "type":"mentor",
  "surname":"asdasdsa",
  "position":"1"
}

###

POST http://127.0.0.1:7000/login
Content-type: application/json

{
  "email": "user@mail.com",
  "password": "fdsfsdf"
}

###

GET http://localhost:7000/user/edit
Content-type: application/json
j-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsIm5hbWUiOiJ0ZXN0IG5hbWUiLCJzdXJuYW1lIjoiYXNkYXNkYSIsImVtYWlsIjoidXNlckBtYWlsLmNvbSIsImlhdCI6MTY1ODEzMTU3MSwiZXhwIjoxNjU4MjE3OTcxfQ.0Xgkxy2_RkvGw6_ARx7ukvSD0XLp6eiY1j41z1B6KkM


###

PUT http://localhost:7000/user/edit
Content-type: application/json
j-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsIm5hbWUiOiJ0ZXN0IG5hbWUiLCJzdXJuYW1lIjoiYXNkYXNkYSIsImVtYWlsIjoidXNlckBtYWlsLmNvbSIsImlhdCI6MTY1ODEzMTU3MSwiZXhwIjoxNjU4MjE3OTcxfQ.0Xgkxy2_RkvGw6_ARx7ukvSD0XLp6eiY1j41z1B6KkM

{
  "name":"fffrrrfff",
  "surname":"asdasda",
  "position_id":"1",
  "type":"mentor",
  "description": "",
  "education": "",
  "experience": "",
  "about": ""
}

###

PUT http://localhost:7000/token
Content-type: application/json

{
  "r-token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsIm5hbWUiOiJmZmZycnJmZmYiLCJzdXJuYW1lIjoiYXNkYXNkYSIsImVtYWlsIjoidXNlckBtYWlsLmNvbSIsImlhdCI6MTY1ODEzMTYzNywiZXhwIjoxNjU4MjE4MDM3fQ.UwfuVmgFEbtA2qUGEaR1WbjzKCZ1klPaHTXU0d6RqiI"
}

###

GET http://localhost:7000/user/profile/38
Content-type: application/json
j-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsIm5hbWUiOiJmZmZycnJmZmYiLCJzdXJuYW1lIjoiYXNkYXNkYSIsImVtYWlsIjoidXNlckBtYWlsLmNvbSIsImlhdCI6MTY1ODEzMTY1OCwiZXhwIjoxNjU4MjE4MDU4fQ.cC0_bmCFyJCUH9zQ34KsoDQZ0N39Uojgeke8jzy36wA

###

GET http://localhost:7000/user/search
Content-type: application/json
j-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsIm5hbWUiOiJmZmZycnJmZmYiLCJzdXJuYW1lIjoiYXNkYXNkYSIsImVtYWlsIjoidXNlckBtYWlsLmNvbSIsImlhdCI6MTY1ODEzMTY1OCwiZXhwIjoxNjU4MjE4MDU4fQ.cC0_bmCFyJCUH9zQ34KsoDQZ0N39Uojgeke8jzy36wA

###

GET http://localhost:7000/user/search?name=ffffff&surname=asdasda&date=2022-07-16&type=mentor
Content-type: application/json
j-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzUsIm5hbWUiOiJmZmZycnJmZmYiLCJzdXJuYW1lIjoiYXNkYXNkYSIsImVtYWlsIjoidXNlckBtYWlsLmNvbSIsImlhdCI6MTY1ODEzMTY1OCwiZXhwIjoxNjU4MjE4MDU4fQ.cC0_bmCFyJCUH9zQ34KsoDQZ0N39Uojgeke8jzy36wA

###
